name:                morse
version:             0.1.0.0
license-file:        LICENSE
author:              Chris Allen
maintainer:          cma@bitemyapp.com

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            Text
build-type:          Simple

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
#description:         Please see the README on Github at <https://github.com/githubuser/project-name#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- QuickCheck

library:
  exposed-modules:       Morse
  ghc-options:
  - -Wall
  - -fwarn-tabs
  source-dirs:           src

executables:
  morse:
    main:                Main.hs
    ghc-options:
    - -Wall
    - -fwarn-tabs
    source-dirs:         src
    dependencies:
    - morse

tests:
  tests:
    ghc-options:
    - -Wall
    - -fno-warn-orphans
    main:                tests.hs
    source-dirs:         tests
    dependencies:
    - base
    - morse
